apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: ticketing
  labels:
    app: ticketing
    component: frontend
spec:
  selector:
    app: ticketing
    component: frontend
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
